### ISSUE TITLE
load from local file?

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/HMP16SData#10]
`load("~/20180312.V13.rda")` etc, looks unintended for the package?

https://github.com/waldronlab/HMP16SData/blame/master/vignettes/HMP16SData.Rmd#L47

**Comment by schifferl** [comment]
This was intentional, it is a hack used to continue development of the vignette while waiting for the `ExperimentHub` database to be updated. Additional comments are there now.

**Comment by schifferl** [comment]
Closed via 0d94acaa8abeb32661eac2d6f89b924e8be7f182
