### ISSUE TITLE
attach_dbGaP and download_dbGaP not working under latest version (2.10.7) SRA toolkit

### ISSUE THREAD

**Issue by stephlee3** [waldronlab/HMP16SData#13]
Hello! The 2.10.7 version of SRA Toolkit no longer supports "vdb-config --import" to import ngc files. Instead, tools such as prefetch, fastq-dump, and vdb-decrypt now have a --ngc option to specify the ngc file for accessing control accessed data.  Therefore, attach_dbGaP and download_dbGaP functions need to be updated.  

Thanks!

**Comment by lwaldron** [comment]
Thanks for the report! @schifferl are you able to make this change (to devel and release) in the near future?

**Comment by schifferl** [comment]
Thanks for the heads up @stephlee3, I will get to this tomorrow.

**Comment by schifferl** [comment]
Fixed by 1b8589c and f7d9dc1, and both commits have been pushed to Bioconductor too. @stephlee3, just give the build system a day and things should work again. Thanks for finding the bug!

**Comment by stephlee3** [comment]
Thanks @schifferl and @lwaldron for the quick update! Just one more question, there is no need to create the protected workspace (paths$dbGaP_directory) under the current version. If you still want that directory, do you want to change its path to user-specific dbGaP repository key instead of "dbGaP-12146"? 

Thank you so much!

**Comment by schifferl** [comment]
Thank you for the pointer @stephlee3. If I make the change, do you have a repository key of your own you could try? There aren't many people with access to the dbGaP study that I can ask to verify this feature and having someone else would be helpful.

**Comment by stephlee3** [comment]
@schifferl  Yes, I have a dbGaP repo key, and the code is working for me if I rename the directory to the name of your repo key and then move the download files to that folder.

**Comment by schifferl** [comment]
Hi again @stephlee3, I've finished the patch (commits c43e996 and 642447e) per your suggestion that the `paths$dbGaP_directory` variable could be removed. Will you try with your `ngc` key tomorrow once Bioconductor has built the package? I'll leave the issue open until you report back.
