### ISSUE TITLE
Raw 16S data

### ISSUE THREAD

**Issue by annabeth495** [waldronlab/HMP16SData#14]
Can you please add a repository with raw 16S sequencing data (fastq) used in this package?

**Comment by schifferl** [comment]
Hi @annabeth495, the raw sequencing samples are available through the sequence read archive and wouldn't make sense to store here. You can read about what samples pertain the the HMP16SData package at https://www.hmpdacc.org/hmp/HMQCP/. However, I am going to close this issue as it is beyond the scope of this package and really more of a feature request. Hope that helps, Lucas.
