### ISSUE TITLE
Decorate to match curatedMetagenomicData

### ISSUE THREAD

**Issue by schifferl** [waldronlab/HMP16SData#5]
Add a function that will modify the objects to match those present in the `curatedMetagenomicData` package.

**Comment by schifferl** [comment]
Not specific enough and more of a feature than a bug, closing. Already exists on Trello as part of the roadmap.

**Comment by lwaldron** [comment]
These Issues however are a public face of project development... since you are implementing these anyways, why not close with reference to a changeset? Issues can be used for features as well as for bugs, there's even the "enhancement" label...

**Comment by lwaldron** [comment]
To be more specific, the enhancement is to document how to change the rownames and colnames of the `V13()` and `V35()` objects to match those of the HMP WMS dataset found in curatedMetagenomicData.

**Comment by schifferl** [comment]
I have been doing some thinking about this lately and I think our process could use just a bit of tweaking... Issues should be just that, *issues* and features should be on Trello. We should make our software-specific project boards publicly visible, just as the issues are, and even make forms for feature request. [Zapier](https://zapier.com/) has a Create Trello cards from Google Forms responses zap that could be used to add cards to a feature request list of cards. This seems like the best way to separate the two concerns to me because open issues look bad.

As for the changing of rownames and colnames, I have a solid draft of the vignette on [RPubs](https://rpubs.com/schifferl/HMP16SData) that matches up the rows and columns without diving too deep into the `SummarizedExperiment` objects. I think essentially, once you arrive at a `phyloseq` object there isn't such a need for it but we can have a chat as to the necessity.

**Comment by lwaldron** [comment]
This is addressed nicely in the [vignette overhaul](https://github.com/waldronlab/HMP16SData/commit/bb90fb35ed61b431af5718564c3cbff693671c12), thanks Lucas!
